changed main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,24 +1,42 @@
 name: Build and Deploy
+
 on: [push]
 permissions:
   contents: write
+
 jobs:
   build-and-deploy:
-    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
+    concurrency: ci-${{ github.ref }}
     runs-on: ubuntu-latest
     steps:
       - name: Checkout 🛎️
         uses: actions/checkout@v4
 
-      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
+      - name: Use Node.js 18.x
+        uses: actions/setup-node@v3
+        with:
+          node-version: '18.x'
+
+      - name: Clear npm cache
+        run: npm cache clean --force
+
+      - name: Install Dependencies 🔧
+        run: npm ci
+
+      - name: Build React App 🏗️
+        run: npm run build
+
+      # Add this step to list the files in the working directory after the build
+      - name: List project files after build
+        run: ls -al
+
+      # Check if the build directory exists
+      - name: Verify Build Directory Exists 📂
         run: |
-          npm ci
-          npm run build
+          if [ ! -d "build" ]; then echo "Build folder not found!"; exit 1; fi
 
       - name: Deploy 🚀
         uses: JamesIves/github-pages-deploy-action@v4
         with:
           branch: gh-pages
-          folder: build # The folder the action should deploy.
-
-          
+          folder: build
